model:
  model: latest_model
  tokenizer: latest_model
  dataset_folder: dataset
  exclude_file: null
  entities:
  - changing value
  - command
  - device
  - duration
  - location
  - scene
  - target number
  - time at
intents:
  - bật thiết bị
  - giảm mức độ của thiết bị
  - giảm nhiệt độ của thiết bị
  - giảm âm lượng của thiết bị
  - giảm độ sáng của thiết bị
  - hủy hoạt cảnh
  - kiểm tra tình trạng thiết bị
  - kích hoạt cảnh
  - mở thiết bị
  - tăng mức độ của thiết bị
  - tăng nhiệt độ của thiết bị
  - tăng âm lượng của thiết bị
  - tăng độ sáng của thiết bị
  - tắt thiết bị
  - đóng thiết bị
  device: cuda
  synonym:
    office hour: office hours
    office: office hours
    office hours: office hour
training:
  train_range: 0.95
  num_train_epochs: 100
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  warmup_steps: 500
  weight_decay: 0.01
  logging_dir: logs/
  early_stopping_patience: 10
  early_stopping_threshold: 0.0001
  output_dir: results/
util:
  intent_threshold: 0.7
  entities_threshold: 0.5
  ambiguous_threshold: 0.2
